# Generated by Django 2.1.3 on 2018-12-15 19:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eproperty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('propertyID', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Property ID')),
                ('propertyName', models.CharField(max_length=50, verbose_name='Title')),
                ('propertyDescription', models.TextField(default='Not Available', verbose_name='Description')),
                ('propertyStreet', models.CharField(max_length=100, verbose_name='Street Name')),
                ('propertyPostalCode', models.CharField(max_length=6, verbose_name='Postal Code')),
                ('propertyStreetNumber', models.PositiveIntegerField(verbose_name='Street Number')),
                ('propertyConstructionDate', models.DateField(default=datetime.date.today, verbose_name='Construction Date')),
                ('propertyPostedDate', models.DateField(default=datetime.date.today, verbose_name='Date Posted')),
                ('propertyNoOfHalls', models.PositiveIntegerField(verbose_name='Halls')),
                ('propertyNoOfRooms', models.PositiveIntegerField(verbose_name='Rooms')),
                ('propertyNoOfBathrooms', models.PositiveIntegerField(verbose_name='Bathrooms')),
                ('propertyNoOfFloors', models.PositiveIntegerField(verbose_name='Floors')),
                ('propertyTotalArea', models.PositiveIntegerField(verbose_name='Total Area')),
                ('propertySellingPrice', models.PositiveIntegerField(verbose_name='Price')),
                ('propertySellingType', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Rent', 'Rent')], default=eproperty.models.DealingChoice('Buy'), max_length=5, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyCategory', models.CharField(choices=[('SingleHouse', 'Single House'), ('AttachedHouse', 'Attached House'), ('TownHouse', 'Town House'), ('Apartment', 'Apartment'), ('Store', 'Store'), ('Farm', 'Farm'), ('Factory', 'Factory'), ('Mall', 'Mall'), ('Building', 'Building'), ('Other', 'Other')], default=eproperty.models.CategoryChoice('Single House'), max_length=15, unique=True, verbose_name='Property Category')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyDirection', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], default=eproperty.models.DirectionChoice('North'), max_length=5, unique=True, verbose_name='Property Direction')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('propertyImageID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('propertyImage', models.ImageField(blank=True, default='/home/tarang/Workspace/S2G4RealEstate/eproperty/static/images/no-image.png', null=True, upload_to='property/', verbose_name='Image')),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertySector', models.CharField(choices=[('Private', 'Private'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Government', 'Government'), ('Rural', 'Rural'), ('Other', 'Other')], default=eproperty.models.SectorChoice('Private'), max_length=15, unique=True, verbose_name='Property Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=50, unique=True)),
                ('countryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='PropertyDirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertyDirection', verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertyCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyCountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyProvince',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertySector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertySector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='countryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='provinceName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Province'),
        ),
    ]
