# Generated by Django 2.1.3 on 2018-12-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyPostedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Posted'),
        ),
    ]
