# Generated by Django 2.1.3 on 2018-12-15 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0002_auto_20181215_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyPostedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
    ]
